# Change these first
owner: telabotanica # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Site web de Tela Botanica
    url: https://www.tela-botanica.org
    icon: https://www.tela-botanica.org/favicon.ico
    assignees:
      - kstefanini
    headers:
      - "User-Agent: Upptime bot / github.com/telabotanica/status"
  - name: Plateforme Tela Formation
    url: https://mooc.tela-botanica.org
    icon: https://web.archive.org/web/20220206151548im_/https://mooc.tela-botanica.org/pluginfile.php/1/theme_telaformation/favicon/1643821402/favicon_plateforme.png
    assignees:
      - kstefanini
    headers:
      - "User-Agent: Upptime bot / github.com/telabotanica/status"
  - name: Observatoire des Saisons
    url: https://www.obs-saisons.fr/
    icon: https://web.archive.org/web/20220218121914im_/https://www.obs-saisons.fr/media/favicon/favicon-32x32.png
    assignees:
      - kstefanini
    headers:
      - "User-Agent: Upptime bot / github.com/telabotanica/status"
  - name: eFlore API
    url: https://api.tela-botanica.org/service:eflore:0.1/bdtfx/taxons/
    icon: https://image.flaticon.com/icons/png/512/1015/1015474.png
    assignees:
      - CDelph
    headers:
      - "User-Agent: Upptime bot / github.com/telabotanica/status"
  - name: CEL API
    url: https://api-cel.tela-botanica.org/api/
    icon: https://image.flaticon.com/icons/png/512/1015/1015474.png
    assignees:
      - kstefanini
    headers:
      - "User-Agent: Upptime bot / github.com/telabotanica/status"
  - name: Annuaire API
    url: https://www.tela-botanica.org/service:annuaire:auth/
    icon: https://image.flaticon.com/icons/png/512/1015/1015474.png
    assignees:
      - kstefanini
    headers:
      - "User-Agent: Upptime bot / github.com/telabotanica/status"
  - name: Smart'Flore API
    url: https://www.tela-botanica.org/smartflore-services/trail
    icon: https://image.flaticon.com/icons/png/512/1015/1015474.png
    assignees:
      - kstefanini
    headers:
      - "User-Agent: Upptime bot / github.com/telabotanica/status"
  - name: Serveur Adansonia
    url: http://tela-botanica.no-ip.org/
    assignees:
      - kstefanini
      - CDelph
      - verovs
      - ya-web
    headers:
      - "User-Agent: Upptime bot / github.com/telabotanica/status"

workflowSchedule:
  graphs: "0 * * * *" # (default: "0 0 * * *")
  responseTime: "0 * * * *" # (default: "0 23 * * *")
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *" # triggered by cloudflare worker https://github.com/upptime/upptime/issues/42#issuecomment-840264035 (default: "*/5 * * * *")

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://upload.wikimedia.org/wikipedia/commons/3/3e/Logo_Tela.png
  favicon: https://avatars.githubusercontent.com/u/3706326?s=400&u=6c0362cee1b5ef60fe05b7bf0e366eb82ebdea9a&v=4
  name: Tela Botanica status page
  introTitle: ""
  introMessage: Contactez-nous si vous constatez des problèmes avec nos services, nous corrigerons ça au plus tôt. Merci de votre patience :)
  navbar:
    - title: Site web de Tela Botanica
      href: https://www.tela-botanica.org
    - title: Plateforme Tela Formation
      href: https://mooc.tela-botanica.org

i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: Tous les systèmes sont opérationnels \o/
  incidentReport: "Incident #$NUMBER détails →"
  activeIncidentSummary: Ouvert à $DATE avec $POSTS mises à jours
  incidentTitle: Incident $NUMBER Détails
  incidentDetails: Incident Details
  incidentFixed: Corrigé
  incidentOngoing: En cours
  incidentOpenedAt: Début
  incidentClosedAt: Fin
  incidentSubscribe: Recevoir les mises à jour
  incidentViewOnGitHub: Consulter sur GitHub
  incidentCommentSummary: Posté à $DATE par $AUTHOR
  incidentBack: ← Retour aux incidents
  pastIncidents: Incidents passés
  pastIncidentsResolved: Corrigé en $MINUTES minutes avec $POSTS mises à jours
  liveStatus: En direct
  overallUptime: "Temps de disponibilité global: $UPTIME"
  overallUptimeTitle: Temps de disponibilité global
  averageResponseTime: "Temps de réponse moyen: $TIMEms"
  averageResponseTimeTitle: Temps de réponse moyen
  sevelDayResponseTime: Temps de réponse sur 7 jours
  responseTimeMs: Temps de réponse (ms)
  up: OK
  down: Indisponible
  degraded: Dégradé
  ms: ms
  loading: Chargement

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
